// Generated by CoffeeScript 1.9.0
(function() {
  var BrowserWindow, app, path;

  app = require('app');

  BrowserWindow = require('browser-window');

  require('crash-reporter').start();

  path = require('path');

  app.on('ready', function() {
    var main_window, preload;
    preload = path.resolve(path.join(__dirname, 'preload.js'));
    main_window = new BrowserWindow({
      width: 800,
      height: 600,
      "node-integration": false,
      "web-security": false,
      preload: preload
    });
    console.log(preload);
    main_window.loadUrl(process.argv[2]);
    return main_window.openDevTools();
  });

}).call(this);
