// Generated by CoffeeScript 1.12.6
(function() {
  var error, spellcheck, webFrame;

  try {
    window.$remote = require('remote');
    webFrame = require('web-frame');
  } catch (error1) {
    error = error1;
    window.$remote = require('electron').remote;
    webFrame = require('electron').webFrame;
  }

  try {
    spellcheck = require('spellchecker');
    webFrame.setSpellCheckProvider("en-US", true, {
      spellCheck: function(text) {
        return !spellcheck.isMisspelled(text);
      }
    });
  } catch (error1) {
    error = error1;
    console.log("Could not load spellchecker: " + error);
  }

  window.onkeyup = function(e) {
    if (e.ctrlKey && e.keyCode === 70) {
      window.show_search_bar();
    }
    if (e.ctrlKey && e.shiftKey && e.keyCode === 73) {
      $remote.getCurrentWindow().toggleDevTools();
    }
    if (e.code === "F11") {
      return $remote.getCurrentWindow().setFullScreen(!$remote.getCurrentWindow().isFullScreen());
    }
  };

}).call(this);
