// Generated by CoffeeScript 1.9.0
(function() {
  var spellcheck, webFrame;

  window.$remote = require('remote');

  webFrame = require('web-frame');

  spellcheck = require('spellchecker');

  webFrame.setSpellCheckProvider("en-US", true, {
    spellCheck: function(text) {
      return !spellcheck.isMisspelled(text);
    }
  });

  window.onkeyup = function(e) {
    if (e.ctrlKey && e.keyCode === 70) {
      return window.show_search_bar();
    }
  };

}).call(this);
